### ISSUE TITLE
CCSDS 123 Issue 2, port to windows.

### ISSUE THREAD

**Issue by drowzie** [NTNU-SmallSat-Lab/fpga-modules#7]
Need to create a port of CCSDS 123 Issue 2 for WINDOWS. 
Using: https://cygwin.com/index.html should provide a easy port since the software does not use linux standards.

**Comment by evelynlimore** [comment]
Joar says there is an app for this so you don't have to change anything. The app is called WSL and needs to be enabled by the extra features in Windows.

**Comment by rogerbirkeland** [comment]
Can help if you need. I like WSL :)

**Comment by drowzie** [comment]
Tried WSSL as my ubuntu dual boot with windows crashed. Works great
https://ubuntu.com/wsl
